version: '3'
services:
  postgres:
    image: postgres:13
    container_name: "postgres"
    hostname: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - 6379:6379
    restart: always

volumes:
  postgres-db-volume: